# Generated by Django 5.0.1 on 2024-02-08 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
