# Generated by Django 5.0.1 on 2024-02-08 14:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0002_alter_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('num_openings', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('requirement_level', models.TextField(blank=True, max_length=2000, null=True)),
                ('desired_qualities', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'ordering': ['-created_at', '-num_openings'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dob', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('highest_education_qualification', models.CharField(choices=[('AA', 'Associate Of Arts'), ('AAS', 'Associate Of Arts and Sciences'), ('AS', 'Associate Of Sciences'), ('BASc', 'Bachelor Of Applied Sciences'), ('BArch', 'Bachelor Of Architecture'), ('BA', 'Bachelor Of Arts'), ('BBA', 'Bachelor Of Business Administration'), ('BCom', 'Bachelor Of Arts'), ('BEd', 'Bachelor of Education'), ('MArch', 'Master of Architecture'), ('MA', 'Master Arts'), ('DA', 'Doctor Of Arts'), ('JD', 'Doctor Of Law'), ('MD', 'Doctor Of Medicine')], max_length=6)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('linked_in', models.CharField(blank=True, max_length=200, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('profile_photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('saved_jobs', models.ManyToManyField(related_name='jobs', to='users.jobs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('startDate', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('endDate', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('role_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.role')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('applied_date', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('cv_used_bool', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobs')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.experience')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('skill', models.ManyToManyField(related_name='exp_skills', to='company.skill')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
